### ISSUE TITLE
KeyError: 'url' - But then sometimes you run again and it works?

### ISSUE THREAD

**Issue by ghost** [liranbg/linkedin-learning-downloader#10]
I am getting an issue where sometimes it downloads and other times it doesn't. 

If it doesn't work, it then sometimes work if I run it again later.

The error I get is:

Traceback (most recent call last):
  File "g:\Google Drive\Documents\Code\Python\Linkedin Video Downloader 3.6\linkedin_learning.py", line 226, in <module>
    loop.run_until_complete(process())
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "g:\Google Drive\Documents\Code\Python\Linkedin Video Downloader 3.6\linkedin_learning.py", line 214, in process
    await fetch_courses()
  File "g:\Google Drive\Documents\Code\Python\Linkedin Video Downloader 3.6\linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "g:\Google Drive\Documents\Code\Python\Linkedin Video Downloader 3.6\linkedin_learning.py", line 119, in fetch_course
    await fetch_chapters(course)
  File "g:\Google Drive\Documents\Code\Python\Linkedin Video Downloader 3.6\linkedin_learning.py", line 131, in fetch_chapters
    await asyncio.gather(*chain.from_iterable(fetch_chapter(course, chapter) for chapter in course.chapters))
  File "g:\Google Drive\Documents\Code\Python\Linkedin Video Downloader 3.6\linkedin_learning.py", line 165, in fetch_video
    video_url = data['elements'][0]['selectedVideo']['url']['progressiveUrl']
KeyError: 'url'

**Comment by welcometopwn** [comment]
Same here.


_Traceback (most recent call last):
  File "linkedin_learning.py", line 226, in <module>
    loop.run_until_complete(process())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 214, in process
    await fetch_courses()
  File "linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "linkedin_learning.py", line 119, in fetch_course
    await fetch_chapters(course)
  File "linkedin_learning.py", line 131, in fetch_chapters
    await asyncio.gather(*chain.from_iterable(fetch_chapter(course, chapter) for chapter in course.chapters))
  File "linkedin_learning.py", line 165, in fetch_video
    video_url = data['elements'][0]['selectedVideo']['url']['progressiveUrl']
KeyError: 'url'_

**Comment by lejaunemauve** [comment]
same issue here.
as it been revolved ?

**Comment by liranbg** [comment]
fixed on #21 && #22
