### ISSUE TITLE
Could not login, Please check your credentials

### ISSUE THREAD

**Issue by tommypratama** [liranbg/linkedin-learning-downloader#13]
Traceback (most recent call last):
  File "linkedin_learning.py", line 226, in <module>
    loop.run_until_complete(process())
  File "/anaconda3/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 210, in process
    await login(USERNAME, PASSWORD)
  File "linkedin_learning.py", line 95, in login
    raise RuntimeError("[!] Could not login. Please check your credentials")
RuntimeError: [!] Could not login. Please check your credentials

**Comment by tommypratama** [comment]
Traceback (most recent call last):
  File "linkedin_learning.py", line 226, in <module>
    loop.run_until_complete(process())
  File "/anaconda3/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 214, in process
    await fetch_courses()
  File "linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "linkedin_learning.py", line 112, in fetch_course
    course = build_course(data['elements'][0])
KeyError: 'elements'

**Comment by moses-aronov** [comment]
Guys Any resolution on this? Also experiencing this issue.

**Comment by liranbg** [comment]
fixed on #21 && #22
