### ISSUE TITLE
Downloads video files partially

### ISSUE THREAD

**Issue by christiaangombert** [liranbg/linkedin-learning-downloader#16]
While downloading the videos of a course. I get an incomple mp4 file for videos that are somewhat bigger than 5mb. The shorter videochapters of the course are downloaded completelly, while the longer ones become blank halfway the video duration.

When i run the lld.py script:
- logging in succeeds
- creating all folders succeeds
- starting to download all the files (Fetching Chapers...) succeeds
- but only a few chapters (the shorter ones) are done fetching before a bunch of errors occur.

I get the following output:

> _2019-03-28 23:52:44,632_ root         INFO     [-] Done fetching course 'Coursename' Chapter no. 6 Video no. 11

The mp4 of Chapter no. 6 Video no. 11 is complete. After a few good downloads, the following errors start to come:

> _2019-03-28 23:53:44,135_ root         ERROR    [!] Error while downloading: ''
> Traceback (most recent call last):
>   File "lld.py", line 197, in download_file
>     chunk = await r.content.read(1024)
>   File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\streams.py", line 369, in read
>     await self._wait('read')
>   File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\streams.py", line 297, in _wait
>     await waiter
>   File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\helpers.py", line 585, in __exit__
>     raise asyncio.TimeoutError from None
> concurrent.futures._base.TimeoutError
> _2019-03-28 23:53:44,146_ root         INFO     [-] Done fetching course 'Coursename' Chapter no. 3 Video no. 12

The mp4 of Chapter no. 3 Video no. 12 is incomplete. Lots of similar errors follow for the rest of the files.

Any suggestions how to properly fetch these videos?

**Comment by christiaangombert** [comment]
The incomplete video files where due to a timeout of the fetching, named aiohttp.ClientTimeout.
This timeout is by default set to 300 seconds (5 minutes) if not defined.
I edited the lld.py script so you can set a custom timeout duration,

@hmspisharody already tackeled this isseu.
