### ISSUE TITLE
Getting Access to <training> is denied after successful login.

### ISSUE THREAD

**Issue by kbhaskar** [liranbg/linkedin-learning-downloader#19]
Initially, could not get past Login Step 1.

Traceback (most recent call last):
  File "linkedin_learning.py", line 227, in <module>
    loop.run_until_complete(process())
  File "C:\Users\test\Python\Python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 211, in process
    await login(USERNAME, PASSWORD)
  File "linkedin_learning.py", line 83, in login
    csrf = html.xpath("//input[@id='loginCsrfParam-login']/@value").pop()
IndexError: pop from empty list

But, when I'm able to proceed further, I still see Access to <trainingName> is denied.
When I try another set of videos, I get back to the "pop from empty list" error again.

Any ideas ? I added another line to look at the line for "html" - so, the line numbers from the original src are 226, 210 and 82.

**Comment by liranbg** [comment]
resolved #21
