### ISSUE TITLE
Error When Downloading a Video that not have Subtitles

### ISSUE THREAD

**Issue by bydioeds** [liranbg/linkedin-learning-downloader#25]
The Error occurs when i try to download this bootstrap-4-essential-training and the download stops, sorry for my bad english btw

`Traceback (most recent call last):
  File "linkedin_learning.py", line 230, in <module>
    loop.run_until_complete(process())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 218, in process
    await fetch_courses()
  File "linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "linkedin_learning.py", line 116, in fetch_course
    await fetch_chapters(course)
  File "linkedin_learning.py", line 128, in fetch_chapters
    await asyncio.gather(*chain.from_iterable(fetch_chapter(course, chapter) for chapter in course.chapters))
  File "linkedin_learning.py", line 139, in fetch_video_or_wait
    await fetch_video(course, chapter, video)
  File "linkedin_learning.py", line 166, in fetch_video
    subtitles = data['elements'][0]['selectedVideo']['transcript']  # transcript is empty when no subtitles available
KeyError: 'transcript'`

EDIT: When i commented these lines everything worked fine 

![Screenshot_2019-08-31_07-56-56](https://user-images.githubusercontent.com/8415008/64064302-2d44f300-cbc5-11e9-982b-b0a782077a30.png)

**Comment by ukazap** [comment]
I have made a pull request to address this error: https://github.com/liranbg/linkedin-learning-downloader/pull/27

**Comment by liranbg** [comment]
Fixed
