### ISSUE TITLE
KeyError ['url']['progressiveUrl']

### ISSUE THREAD

**Issue by Indiana3714** [liranbg/linkedin-learning-downloader#30]
Line 165, there is no longer a keys for ['url']['progressiveUrl']

**Comment by quinn-p-mchugh** [comment]
Got the same error. Creation of the course's folder hierarchy works great, but have yet to successfully download any videos.

![image](https://user-images.githubusercontent.com/40648753/67613121-e532ee80-f777-11e9-8673-7832f3f1b42d.png)

**Comment by Jramirezg** [comment]
Same issue here. 
Traceback (most recent call last):
  File "linkedin_learning.py", line 234, in <module>
    loop.run_until_complete(process())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 222, in process
    await fetch_courses()
  File "linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "linkedin_learning.py", line 116, in fetch_course
    await fetch_chapters(course)
  File "linkedin_learning.py", line 128, in fetch_chapters
    await asyncio.gather(*chain.from_iterable(fetch_chapter(course, chapter) for chapter in course.chapters))
  File "linkedin_learning.py", line 139, in fetch_video_or_wait
    await fetch_video(course, chapter, video)
  File "linkedin_learning.py", line 165, in fetch_video
    video_url = data['elements'][0]['selectedVideo']['url']['progressiveUrl']
KeyError: 'url'

Are you using an educational linkedin learninig account? y linkedin profile is linked  to a university, I am guessing that is the reason why it is failing.

**Comment by DM2602** [comment]
Have the same problem, this happens only on specific videos. I had courses run fine but then some other videos from other courses recreate this error.
