### ISSUE TITLE
Access is denied by CAPTCHA on Linkedin account

### ISSUE THREAD

**Issue by DrewLukas** [liranbg/linkedin-learning-downloader#32]
Hi, can't download any course anymore because Linkedin set a CAPTCHA on my account. Hope this will not be forever. Beware of not downloading to many courses in short time or Linkedin will track it and take action. Able to log in normally on Linkedin Learning in my browser after passing the captcha.

Does anyone have the same problem?

Traceback (most recent call last):
  File "linkedin_learning.py", line 225, in <module>
    loop.run_until_complete(process())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 209, in process
    await login(USERNAME, PASSWORD)
  File "linkedin_learning.py", line 95, in login
    raise RuntimeError("[!] Could not login. Please check your credentials")
RuntimeError: [!] Could not login. Please check your credentials

**Comment by MagicRico** [comment]
> 
> 
> Hi, can't download any course anymore because Linkedin set a CAPTCHA on my account. Hope this will not be forever. Beware of not downloading to many courses in short time or Linkedin will track it and take action. Able to log in normally on Linkedin Learning in my browser after passing the captcha.
> 
> Does anyone have the same problem?
> 
> Traceback (most recent call last):
> File "linkedin_learning.py", line 225, in
> loop.run_until_complete(process())
> File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
> return future.result()
> File "linkedin_learning.py", line 209, in process
> await login(USERNAME, PASSWORD)
> File "linkedin_learning.py", line 95, in login
> raise RuntimeError("[!] Could not login. Please check your credentials")
> RuntimeError: [!] Could not login. Please check your credentials

Hi DrewLukas,
I am just using this python script since a few days and now get a captcha too.
Did you achieve to solve it, bypass this captcha?

**Comment by jjguz17** [comment]
Hi, I got the same message, but since Linkeding is using a captcha for every new sessión for security reasons you won't be able to login from this tool, I started to search another way to do this from a saved sessión with cookies and youtube-dl can do this and supports Linkedin learning/lynda courses. 

Use youtube-dl instead, this allows to use a cookies.txt file to save the Linkedin session and download the video content.
https://www.mullineaux.com.au/posts/2020/01/25/create-your-own-netflix-for-nerds/
