### ISSUE TITLE
RuntimeError: [!] Could not login. Please check your credentials CAPTCHA!

### ISSUE THREAD

**Issue by AirIn19** [liranbg/linkedin-learning-downloader#38]
Traceback (most recent call last):
  File "linkedin_learning.py", line 225, in <module>
    loop.run_until_complete(process())
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 209, in process
    await login(USERNAME, PASSWORD)
  File "linkedin_learning.py", line 95, in login
    raise RuntimeError("[!] Could not login. Please check your credentials")
RuntimeError: [!] Could not login. Please check your credentials

**Comment by Ahmed-Soli** [comment]
I have restructured the project , You can see it here 
https://github.com/Ahmed-Soli/linkedin-course-downloader
