### ISSUE TITLE
asyncio      ERROR    SSL error in data received

### ISSUE THREAD

**Issue by ahmadsb101** [liranbg/linkedin-learning-downloader#42]

**Comment by ahmadsb101** [comment]
2020-04-11 14:01:57,462 asyncio      DEBUG    Using selector: EpollSelector
2020-04-11 14:01:57,463 root         INFO     [*] -------------Login-------------
2020-04-11 14:01:57,463 root         INFO     [*] Login step 1 - Getting CSRF token...
2020-04-11 14:01:59,546 root         DEBUG    [*] CSRF: 26618f33-f88e-42a2-8050-5a8059d7c2f7
2020-04-11 14:01:59,546 root         INFO     [*] Login step 1 - Done
2020-04-11 14:01:59,546 root         INFO     [*] Login step 2 - Logging In...
2020-04-11 14:02:11,210 root         INFO     [*] Login step 2 - Done
2020-04-11 14:02:11,211 root         INFO     [*] -------------Done-------------
2020-04-11 14:02:11,212 root         INFO     [*] -------------Fetching Course-------------
2020-04-11 14:02:11,216 asyncio      ERROR    SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fa6a1f2ae48>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
Traceback (most recent call last):
  File "linkedin_learning.py", line 234, in <module>
    loop.run_until_complete(process())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 222, in process
    await fetch_courses()
  File "linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "linkedin_learning.py", line 111, in fetch_course
    data = await resp.json()
  File "/home/ahmad/.local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1031, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://www.linkedin.com/learning-api/detailedCourses??fields=fullCourseUnlocked,releasedOn,exerciseFileUrls,exerciseFiles&addParagraphsToTranscript=true&courseSlug=python-projects&q=slugs')
2020-04-11 14:02:12,166 asyncio      ERROR    Unclosed connection
client_connection: Connection<ConnectionKey(host='www.linkedin.com', port=443, is_ssl=True, ssl=None, proxy=URL(''), proxy_auth=None, proxy_headers_hash=2453169245501700767)>
