### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by slotbite** [liranbg/linkedin-learning-downloader#44]
```
<Element html at 0x147f197a728>
Traceback (most recent call last):
  File "c:/Users/cvargasa/Documents/IMG/Scrapy/linkedin-learning-downloader/linkedin_learning.py", line 227, in <module>
    loop.run_until_complete(process())
  File "C:\Users\cvargasa\AppData\Local\conda\conda\envs\cnn - copia\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "c:/Users/cvargasa/Documents/IMG/Scrapy/linkedin-learning-downloader/linkedin_learning.py", line 211, in process
    await login(USERNAME, PASSWORD)
  File "c:/Users/cvargasa/Documents/IMG/Scrapy/linkedin-learning-downloader/linkedin_learning.py", line 83, in login
    csrf = html.xpath("//input[@id='loginCsrfParam-login']/@value").pop()
IndexError: pop from empty list
```

**Comment by liepaja** [comment]
Replace linkedin url with a sign up form url like "https://www.linkedin.com/login?fromSignIn=true&trk=guest_homepage-basic_nav-header-signin"

**Comment by MustafaUzun447** [comment]
How we replace? can you explain more?
