### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by shadowdragon007** [liranbg/linkedin-learning-downloader#49]
C:\Users\Dragoon\Downloads\Compressed\linkedin-learning-downloader-master>python linkedin_learning.py
Traceback (most recent call last):
  File "linkedin_learning.py", line 12, in <module>
    from config import USERNAME, PASSWORD, COURSES, PROXY, BASE_DOWNLOAD_PATH
  File "C:\Users\Dragoon\Downloads\Compressed\linkedin-learning-downloader-master\config.py", line 8
    COURSES = https://www.linkedin.com/learning/introducing-the-pmbok-guide-seventh-edition
                   ^
SyntaxError: invalid syntax

**Comment by shadowdragon007** [comment]
C:\Users\Dragoon\Downloads\Compressed\linkedin-learning-downloader-master>python linkedin_learning.py
2020-08-19 01:49:36,091 asyncio      DEBUG    Using selector: SelectSelector
2020-08-19 01:49:36,095 root         INFO     [*] -------------Login-------------
2020-08-19 01:49:36,095 root         INFO     [*] Login step 1 - Getting CSRF token...
2020-08-19 01:49:36,857 root         DEBUG    [*] CSRF: f3d29bf2-e32c-43cf-820e-a6f63ced5ef8
2020-08-19 01:49:36,857 root         INFO     [*] Login step 1 - Done
2020-08-19 01:49:36,859 root         INFO     [*] Login step 2 - Logging In...
2020-08-19 01:49:37,849 root         INFO     [*] Login step 2 - Done
2020-08-19 01:49:37,849 root         INFO     [*] -------------Done-------------
2020-08-19 01:49:37,850 root         INFO     [*] -------------Fetching Course-------------
Traceback (most recent call last):
  File "linkedin_learning.py", line 283, in <module>
    loop.run_until_complete(process())
  File "C:\Program Files\Python36\lib\asyncio\base_events.py", line 484, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 271, in process
    await fetch_courses()
  File "linkedin_learning.py", line 119, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "linkedin_learning.py", line 128, in fetch_course
    data = await resp.json()
  File "C:\Program Files\Python36\lib\site-packages\aiohttp\client_reqrep.py", line 1031, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://www.linkedin.com/learning-api/detailedCourses??fields=fullCourseUnlocked,releasedOn,exerciseFileUrls,exerciseFiles&addParagraphsToTranscript=true&courseSlug=https://www.linkedin.com/learning/introducing-the-pmbok-guide-seventh-edition&q=slugs')
